### ISSUE TITLE
Error Adyen_Payment_Helper_Payment_Data->getInfoBlock(Object(Mage_Sales_Model_Order_Payment))

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#729]
Magento 1.9.3.1

[13-Jan-2017 08:29:19] WARNING: [pool shirts] child 30834 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getInfoBlockType() on boolean in /app/code/community/Adyen/Payment/Helper/Payment/Data.php:115"
[13-Jan-2017 08:29:19] WARNING: [pool shirts] child 30834 said into stderr: "Stack trace:"
[13-Jan-2017 08:29:19] WARNING: [pool shirts] child 30834 said into stderr: "#0 /app/code/core/Mage/Adminhtml/Block/Sales/Order/Payment.php(50): Adyen_Payment_Helper_Payment_Data->getInfoBlock(Object(Mage_Sales_Model_Order_Payment))"
[13-Jan-2017 08:29:19] WARNING: [pool shirts] child 30834 said into stderr: "#1 /app/code/core/Mage/Adminhtml/Block/Sales/Order/Payment.php(44): Mage_Adminhtml_Block_Sales_Order_Payment->setPayment(Object(Mage_Sales_Model_Order_Payment))"
[13-Jan-2017 08:29:19] WARNING: [pool shirts] child 30834 said into stderr: "#2 /app/code/core/Mage/Core/Block/Abstract.php(922): Mage_Adminhtml_Block_Sales_Order_Payment->_beforeToHtml()"
[13-Jan-2017 08:29:19] WARNING: [pool shirts] child 30834 said into stderr: "#3 /app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()"
[13-Jan-2017 08:29:19] WARNING: [pool shirts] child 30834 said into stderr: "#4 /app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('order_payment', true)"
[13-Jan-2017 08:29:19] WARNING: [pool shirts] child 30834 said into stderr: "#5 /var..."

**Comment by rikterbeek** [comment]
Hi @seansan,

Please stop just dropping errors and provide more context into your issues then we might be able to help you out.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
This fatal error is occuring in our logs. $instance = $this->getMethodInstance($info->getMethod()) is not returning an object here. If this case can occur then then the error should be catched.

**Comment by shanelja** [comment]
I disagree that this exception should be caught in `Adyen_Payment_Helper_Payment_Data::getInfoBlock`.

This method is explicitly expected to return an object of `Mage_Core_Block_Template`, in most cases it would be nice to catch the error, but then what do you return? You can't magic a block from nowhere. I would suggest fixing the issue in `getMethodInstance` such that the `Mage_Payment_Model_Info` object passed to `getInfoBlock` contains a valid Method name. It seems to me that there is simply a method type which isn't being catered for here.

@seansan can you please dump out the Method name which gets passed to `getMethodInstance` so we can see which block isn't being supported (and if it's within the remit of the adyen-magento module to even support it)?

**Comment by seansan** [comment]
Maybe we can look at it in a wider context: why is this core method
overridden? And is this necessary?

I hope it helps

**Comment by shanelja** [comment]
Hi, @seansan, upon investigating, this method is entirely backwards compatible with the current Magento implementation - it's additive, but retains support for generic payment method instance types. Whatever method name is causing your exception would also cause an exception without Adyen's override.

Can you please dump out the Method name which gets passed to getMethodInstance so we can see what the issue is?

**Comment by seansan** [comment]
I think it is some old pré adyen payment - one would expect it to fallback
to default  ..... there is something strange there that we need to
investigate

Sorry maybe this is then not Adyen issue; ony question though is it really
necessary to override this core file?

You can close the issue

**Comment by shanelja** [comment]
Having looked in to the functionality, the answer to your question is: It's not _necessary_ - but it is _easy_. What the code within `Adyen_Payment_Helper_Payment_Data::getMethodInstance` is doing could be done within the constructor of the `adyen_hpp` and `adyen_oneclick` payment method classes by loading up the parent orders payment info and then processing any custom payment method logic.

However, the calls made to `getMethodInstance` need to be generic since it's called in almost 100 places in the Magento core! Taking this in to account, it seems like the amount of work (and edge-cases to support) required to do this without the overload would make it unfeasible, and since it's already functional how it is, it's unlikely that the Adyen team will take the time to perform such a sizeable refactor when there are outstanding feature and bug requests already.
