### ISSUE TITLE
Undefined index: brandCode

### ISSUE THREAD

**Issue by lykhouzov** [Adyen/adyen-magento#815]
When i was attempting to use HPP with **Leave payment method selection on HPP** YES i've got following error and do not have ability to place an order.
```php
2017-08-22T08:59:58+00:00 DEBUG (7): Exception message: Notice: Undefined index: brandCode  in /var/www/r4_stage/webroot/app/code/community/Adyen/Payment/Model/Adyen/Hpp.php on line 207
Trace: #0 /var/www/r4_stage/webroot/app/code/community/Adyen/Payment/Model/Adyen/Hpp.php(207): mageCoreErrorHandler(8, 'Undefined index...', '/var/www/r4_sta...', 207, Array)
#1 /var/www/r4_stage/webroot/app/code/community/Adyen/Payment/Block/Redirect.php(147): Adyen_Payment_Model_Adyen_Hpp->getFormUrl()
#2 /var/www/r4_stage/webroot/app/code/core/Mage/Core/Block/Abstract.php(923): Adyen_Payment_Block_Redirect->_toHtml()
#3 /var/www/r4_stage/webroot/app/code/community/Adyen/Payment/controllers/ProcessController.php(160): Mage_Core_Block_Abstract->toHtml()
#4 /var/www/r4_stage/webroot/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Adyen_Payment_ProcessController->redirectAction()
#5 /var/www/r4_stage/webroot/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('redirect')
#6 /var/www/r4_stage/webroot/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /var/www/r4_stage/webroot/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#8 /var/www/r4_stage/webroot/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /var/www/r4_stage/webroot/index.php(83): Mage::run('com_br', 'website')
#10 {main}
```

In my opinion, it happens because of this code is added conditionally but requested in line 207 always.
`app/code/community/Adyen/Payment/Helper/Payment.php:359`
```php
       // Add brandCode if payment selection is done
        if ($brandCode) {
            $adyFields['brandCode'] = $brandCode;
        }
```
but here `app/code/community/Adyen/Payment/Model/Adyen/Hpp.php:207`
```php
        $brandCode          = $this->getFormFields()['brandCode'];
```

**Comment by rikterbeek** [comment]
Hi @lykhouzov,

Thanks for letting us know. I see indeed the issue. We will fix it today and let you know how we solved it. 

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @lykhouzov,

Could you check if the fix above is fixing your issue ?

Regards,
Rik
Adyen

**Comment by lykhouzov** [comment]
Thank you @rikterbeek  for the fix, i will test locally and let you know.

Regards, 
Aleksandr

**Comment by rikterbeek** [comment]
Hi @lykhouzov,

Let me know if it works that we can do a hotfix release this week.

Regards,
Rik
Adyen

**Comment by lykhouzov** [comment]
Hello @rikterbeek .
I've tested it locally and it seems to be working.
So that i will be waiting until release of this fix

Thank you.

**Comment by rikterbeek** [comment]
Hi @lykhouzov,

Great! 

Regards,
Rik
Adyen
