### ISSUE TITLE
Notice: Undefined index: column_name

### ISSUE THREAD

**Issue by lykhouzov** [Adyen/adyen-magento#820]
on fresh installation of the module i got this Notice, which blocks me do anything on  System->Configuration->Payment Methods.

```
Notice: Undefined index: column_name  in /var/www/html/r4/app/code/community/Adyen/Payment/Model/Source/Zeroauthdatefield.php on line 58

#0 /var/www/html/r4/app/code/community/Adyen/Payment/Model/Source/Zeroauthdatefield.php(58): mageCoreErrorHandler(8, 'Undefined index...', '/var/www/html/r...', 58, Array)
#1 /var/www/html/r4/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(463): Adyen_Payment_Model_Source_Zeroauthdatefield->toOptionArray(false)
#2 /var/www/html/r4/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#3 /var/www/html/r4/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(285): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element), Object(Varien_Data_Form_Element_Fieldset))
#4 /var/www/html/r4/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#5 /var/www/html/r4/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#6 /var/www/html/r4/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#7 /var/www/html/r4/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#8 /var/www/html/r4/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_ConfigController->editAction()
#9 /var/www/html/r4/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/html/r4/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/html/r4/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/html/r4/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#13 /var/www/html/r4/index.php(83): Mage::run('', 'website')
#14 {main}
```
```xml
        <Adyen_Payment>
            <version>2.9.2</version>
        </Adyen_Payment>
```
it is because result of fetching data has capitalized index while in code lower-cased is used.
```php
/var/www/html/r4/app/code/community/Adyen/Payment/Model/Source/Zeroauthdatefield.php:57:
array (size=1)
  'COLUMN_NAME' => string 'customer_dob' (length=12)

$rows[] = ['value' => $row['column_name'], 'label' => $row['column_name']];
```

PS: also it's not the best practice way of magento to use raw SQL especially with not escaped strings.

**Comment by rikterbeek** [comment]
Hi @lykhouzov,

Understand you point could you check if the above code change solve your issues ?

Regards,
Rik
Adyen

**Comment by lykhouzov** [comment]
Hello, @rikterbeek 
I've tested it locally and it's working fine.

Thank you.
Regards, Aleksandr.

**Comment by lykhouzov** [comment]
Hello @rikterbeek, do you know when this fix could be included to a release?
