### ISSUE TITLE
Mage_Core_Exception: ResultUrl authentification failure

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#901]
**Magento version**: 1938
**Plugin version**: latest
**Description**

We are seeing periodic cases of below in our logs. Maybe an exception but saw it now several times. Our ResultUrl is empty and setup with adyen support. 

So I am uncertain what is the cause of this authentification failure

Mage_Core_Exception: ResultUrl authentification failure in app/Mage.php:595
Stack trace:
#0 app/code/community/Adyen/Payment/Model/ValidateResultUrl.php(72): Mage::throwException('ResultUrl authe...')
#1 app/code/community/Adyen/Payment/controllers/ProcessController.php(591): Adyen_Payment_Model_ValidateResultUrl->validateResponse(Array)
#2 app/code/community/Adyen/Payment/controllers/ProcessController.php(280): Adyen_Payment_ProcessController->validateResultUrl(Array)
#3 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Adyen_Payment_ProcessController->successAction()
#4 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('success')
#5 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#7 app/Mage.php(683): Mage_Core_Model_App->run(Array)

**Comment by rikterbeek** [comment]
Hi @seansan,

This could have many reasons.  Most common are wrong result url defined in the skin or the url is being hit in the browser without any parameters causing this error.

Regards,
Rik
Adyen
